### ISSUE TITLE
Handle the use of unavailable functions

### ISSUE THREAD

**Issue by 4br3mm0rd** [4br3mm0rd/mpyg321#22]
In several cases in the code, functions are only available for mpg123 and not for mpg321 (mute/unmute, load_list).

I believe it could be better if:
 - When possible, we perform the action in another way (for example, in mute, we can call `self.volume(0)` and call artificially the `on_user_mute` callback)
 - When not possible, throw an error? On one hand, this would make programs crash at some points. On the other hand, there is a function which is supposed to do something and doesn't, which is also an issue, and is definetly worth crashing!

What do you guys think?

**Comment by 4br3mm0rd** [comment]
@stefets @hakmad let me know what you think

**Comment by stefets** [comment]
Greetings @4br3mm0rd  and @hakmad,

My deep reflexions goes on that direction and your opinions are importants. 

The wrapper works well but managing 2 players in a single object makes things difficult when it's time to add features for a specific player.

I think the wrapper is missing a base class for the common features. With a base  class, we can inherit it and implement mpg123 and mpg321 as well. It's a separation of concerns.

It's important to considere that mpg321 player is **not** maintained since many years and it's a risk in a production environment.

On the other side, mpg123 is an **active** project with an experimented maintainer.

Another option is to create a new top level project **mpyg123** that will wrap mpg123 

Users will have the choice to work with the wrapper of his choice.

On my side, I am willing to work on the mpg123 side implementation and the base class.

What do you think ?

**Comment by 4br3mm0rd** [comment]
I agree with you that we need to reorganize the code to make it clearer, and to focus on mpg123 development because it is the only one that is currently maintained.

The architecture with a base class sounds good to me. Do you think that we can find an implementation that would be retrocompatible with what we currently have? Is there a way to keep as many features as possible compatible with the current way of the library?

I am totally ok with the idea of not being retrocompatible, but since the project is quite young, I am afraid we would lose many users, which could kill the project. That's why I'm trying to see if we can keep the features.

We could also deprecate the current usage, slowly...

**Comment by hakmad** [comment]
Hey @stefets and @4br3mm0rd .

I'm personally of the opinion that we should drop support for `mpg321` entirely (the last release was in 2012 and there was an 8 year gap between releasing 0.2.10 and 0.2.11) but I do agree with @4br3mm0rd in that we would lose users, and I'm more than happy to try something else so here's a few idea of mine.

I think the base class idea also sounds good, but the issue becomes how do we actually design this? One idea could be to a pseudo interface superclass `BasePlayer` that contains all the possible methods (`pause`, `load`, `jump`, etc.). We could then have subclasses (`MPG123Player` and `MPG321Player`) implement `BasePlayer` and fill out only the functionality that they need. The methods in `BasePlayer` could (by default) all be set to throw an exception so if a user tries to call a method that hasn't been implemented (for example, `mute` when using `MPG321Player`) then an error occurs. I don't think this is a great idea because then we might get a lot of duplicated code, but it's a start nonetheless. Take a look at [diagram 1](https://user-images.githubusercontent.com/88987013/143494518-04a750b7-2764-4792-8126-46adff1b7930.png) for a (very poor :sweat_smile: ) UML diagram of what this might look like.

Another idea could be to keep most of what we have and rename the main class to something like `MPG321Player`. We remove all the extra functionality that `mpg123` contains from this class. We could then have another class, `MPG123Player` which inherits `MPG321Player` but also adds the extra functionality of `mpg123`. Essentially we're just moving all the `mpg123` stuff to a new class and keeping `mpg321`'s functionality to the base class. This is probably a better solution as we don't have to completely rewrite what we have, we just have to restructure it slightly. See [diagram 2](https://user-images.githubusercontent.com/88987013/143494520-929578f4-ae2a-4c46-8b0d-ec31333d472f.png) for a diagram of what this would look like.

A final idea is to combine the previous 2 ideas: have a base class `BasePlayer` which is filled out with functionality and have 2 subclasses `MPG321Player` and `MPG123Player` which inherit this. Then you could either choose to completely fill out the functionality in `BasePlayer` (for example, have a `mute` method in `BasePlayer` and in `MPG321Player` override it to throw an exception - see [diagram 3](https://user-images.githubusercontent.com/88987013/143494521-65f5827a-17ef-41b8-be55-7389327922f7.png)) or keep it minimal (only fill out functionality that is common in both players, let `MPG123Player` add any extra methods it has - see [diagram 4](https://user-images.githubusercontent.com/88987013/143494522-00cc7dd8-bc19-4656-8a5b-fa18e6f592a2.png)).

I think the first idea is definitely the worst out of the three - we'd end up duplicating a lot of code for no reason, so I guess the choice is between the last 3. I'm no good with decisions and these ideas still need a *lot* of refinement before they can be put into practice so take a look and let me know what you think!

**Comment by hakmad** [comment]
By the way, the common functionality between `mpg123` and `mpg321` is as follows:

- `LOAD` - load a file.
- `JUMP` - jump to a position.
- `STOP` - stop playing.
- `QUIT` - quit the player (not really needed in our case).
- `PAUSE` - pause.

This is actually most of the functions in `mpg321`, the only thing that's missing is `GAIN` (which I'm pretty sure is volume control). 

There is also some inconsistency with how `JUMP` works: as far as I can tell, `mpg321` doesn't work with seconds, only frames (though it can jump both to an absolute frame and a relative frame). I could be wrong on this as I'm just looking at the source code (I've never been able to get `mpg321` to compile on my machine) but essentially, the base class from ideas 2, 3 and 4 would need to have the following functions:

- `load()`
- `stop()`
- `pause()`
- Maybe `quit()`? I don't see why we would need it though.

I hope that helps!

Edit: clarified myself a bit.

**Comment by stefets** [comment]
Hello guys,

Thanks @hakmad  for your analysis.

For the diagram2 suggestion I am not sure because we stay tight coupled with the mpg321 logic.

I'm not so afraid of the first suggestion. I see the base class like an abstract class and implement identical methods of both players in that bass class. All the others methods will be there as prototype and will throw a kind of NotImplementedException. Then we implement/override the methods in each class and we can super() the base methods depending the situation.

Also, I see the base class responsible of all the pexpect logic for BOTH players. 

The child class will be light and specialized for its player.

**Comment by 4br3mm0rd** [comment]
Thanks guys for the great thinking around this question.

Here is what I think (I believe I agree with @stefets and it is mostly what is described in @hakmad 's diagram 1):
 - One `BasePlayer` main class. It implements ALL the functions that can be called in ANY of the players. 
 - For the common functions that contain the same code for both child classes, we write the code in the `BasePlayer` class so that we don't need to override it.
 - For the functions that are only in MPG123, we create the method inside `BasePlayer` that will throw an exception (`WrongPlayerVersionException: the player version does not allow this method.`). In the `Mpg123Player` class, we would implement the actual function.
 - Functions that are common to both classes but implemented in different ways (`volume()` which is `GAIN` in 321 and `VOLUME` in 123, or `jump()` that seems to need some more checks according to @hakmad, ...), we would create it in the `BasePlayer` without any code in it, and override it in both subclasses

Of course, this assumes like @stefets said that the BasePlayer would take care of the pexpect logic.

This strategy has some weaknesses in terms of code "cleanness":
- I don't feel so good about the way it handles the functions that are not in both players. Why would `BaseClass` be MPG321 by default? On the other hand, it seems weird to me to override a function inside MPG321 that would throw an exception. A choice has to be made, I'm not sure which one is the cleanest (let me know what you think)
- I don't like empty methods that will be overridden, but it might be just me and be a good practice in general :) 

Let me know what you think, any idea for improvement, and if you think we should go with this!

**Comment by stefets** [comment]
Hi guys,

I agree with you @4br3mm0rd 

For the 'clean' code we have to deal with two different process doing the same things wich one is a fork of the other and the bass class will make this transparent. The BasePlayer is the conductor, it will abstract the differences.

For example with the volume() gain() example we implement both in the bass class but we override volume() only in the 321 player.
```
def mpg321.volume(value):
    self.gain(value)

def mpg321.gain(value):
    super().gain(value)
```

Of course, I will not call gain() in the 123 player. The base class should check the player and throw if 123 player call gain()

Since the BasePlayer makes sense, I set a new branch named **diagram** in my fork and added an UML diagram made with  https://www.diagrams.net/

https://github.com/stefets/mpyg321/tree/diagram/docs

It can help us to design the new model and I can PR it to the mainstream branch.

Should we create a new top level project MpyG12321 and deprecate this one ?

What do you think ?

**Comment by hakmad** [comment]
> I don't feel so good about the way it handles the functions that are not in both players. Why would BaseClass be MPG321 by default? On the other hand, it seems weird to me to override a function inside MPG321 that would throw an exception. A choice has to be made, I'm not sure which one is the cleanest (let me know what you think)

One possible option would be to have `BasePlayer` only implement the absolute common functionality between `mpg123` and `mpg321` (so only `LOAD`, `STOP` and `PAUSE`). Then, in the subclasses (`MPG123Player` and `MPG321Player`) we would implement all other functionality - `JUMP` and `VOLUME` (and all the stuff that `mpg123` has that `mpg321` doesn't) would be inside the subclasses, not in the base class.

Would that be okay? Or am I just kicking the can further down the road? 😅

**Comment by 4br3mm0rd** [comment]
Hey guys! Sorry for the delay I have been quite busy lately.

I agree with both of you, and I believe the approach from hakmad is the cleanest. So here is what we go for:
- `BasePlayer` that only implements the common functionalities (that are also called the same way in mpg123 and mpg321, meaning, for example, we do not implement the `VOLUME` in `BasePlayer` because it is called `GAIN` in mpg312).
- `Mpg312Player` and `Mpg123Player` that actually implement all the differences.

This would have some impact when upgrading, because the class `Mpg321Player` would lose some functionalities for the mpg123 users (such as volume or other stuff), but I believe this is acceptable (given the fact that most users probably only use play, pause, and other basic functions).

Does any of you want to work on it?

**Comment by stefets** [comment]
Hello! I also agree that is the cleanest way to go.

I think that the most important is that there is no breaking changes. On my side I inherit the library and if there are breaking changes, I will fix them. It can't be a major changes IMHO.

I am willing to work on the project. We have to determine who is doing what. I think that one can be responsible for the base class and one responsible for the implementation for both players. On my side I failed to build mpg321 months ago on Linux... I will need to dig in and I have to build mpg321 before going further. Let me check this next week :)

**Comment by 4br3mm0rd** [comment]
I can work on the mpg321 class since you guys are using mpg123. 
I can also implement the base class since it is not such a big work. I will create a new branch and we can PR to it (so that we publish it only once we have all the features up and working)

**Comment by stefets** [comment]
That sound good to me, I can take the mpg123 implementation on my side.

I suggest to let you push the base and mpg321 classes before starting any coding on my side.

Thanks !
